title: Extraction and use of arguments in Recommender Systems
description: This repository contains a simple but efficient implementation of an argument-based recommender system
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
