name: "\U0001F41BBug report"
description: Create a report to help us improve arg-miner.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please write a clear and concise description of what the bug is.
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the arg-miner is?
      options:
        - arg-miner v1.0.x
        - arg-miner v2.0.x
        - arg-miner v2.6.x
      default: 0
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Please write a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide us your environment information. You can view this information by entering the following command:
        ```shell
        systeminfo
        ```
        Note: avoid pasting/sharing personal data.
      value: |
        - OS: [e.g. Windows 11]
        - JDK or JRE: [e.g. 17]
        - Screen resolution: [e.g. 1680 x 1050]
        - (Optional) Other libraries and their versions:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error messages, stack traces, or logs
      description: Please copy and paste any relevant error messages, stack traces, or log output.
      render: shell
    validations:
       required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide how we reproduce your reported bugs. If possible, it is highly recommended to provide the reproducible example codes.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
        ```java
        // Java code
        ```
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (optional)
      description: Please add any other context or screenshots if you have.
    validations:
      required: false
