name: "\U00002753Questions"
description: Don't use GitHub Issues to ask support questions.
body:
  - type: markdown
    attributes:
      value: |
        # Please use GitHub Discussions
        Don't use GitHub Issues to ask support questions. Use the [GitHub Discussions](https://github.com/argrecsys/arg-miner/discussions) for that.
  - type: textarea
    attributes:
      label: "Don't use GitHub Issues to ask support questions."
